<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- Auth -->
		<PackageReference Include="Mapster" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />

		<!-- EF Core (PostgreSQL only) -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.14.3" />

		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CmsBackend.Domain\CmsBackend.Domain.csproj" />
	</ItemGroup>

</Project>